framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000       # ms
                    multiplier: 2     # 1s → 2s → 4s

        routing:
            App\Application\Command\CommitReservation\CommitReservationCommand: async
