framework:
  workflows:
    product_reservation_workflow:
        type: 'state_machine'
        supports:
            - App\Entity\ProductReservation
        initial_marking: 'pending'
        places:
            - 'pending'
            - 'commited'
            - 'cancelled'
        transitions:
            commit:
                from: 'pending'
                to: 'commited'
            cancel:
                from: 'pending'
                to: 'cancelled'
